### ISSUE TITLE
Motivation for this library

### ISSUE THREAD

**Issue by SamMousa** [flobee/spss#1]
Hi,

Your library is the youngest on packagist for SPSS file reading / writing; did you evaluate other libraries?
https://github.com/sakalauskas/spss
https://github.com/tiamo/spss

If so, what was your motivation for rolling your own?

**Comment by flobee** [comment]
Hi
Thanks for your request!
Its not an own work. See the docs/license. 
Its a fork of tiamo but to avoid conflicts i decided to split the tree. 
Improves the tests at first to be able using phpunit 5 or 6 in next step and having an improved version handling.
There will come some more helpers to get into it through my php library (mumsys, but not public yet) and i plan to do some interfaces for the items and improve data handling bevor the parser starts to speed up stuff a lot. All of it , when done, i will introduce back to tiamo to get in touch and maybe get a merge. All the trees are currenly compatible.
I dont like "master" branches. one of the reasons. I like unstable,testing,stable and semver.org version handling :) And this doesnt fit from scratch for me.
Kind regards Florian
