### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by semoriil** [flobee/spss#10]
It's claimed to support PHP 7.2, 7.3 and up, but composer seems to be unaware about it...
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - flobee/spss 3.1.4 requires php 7.3.* -> your PHP version (7.4.6) does not satisfy that requirement.
    - flobee/spss 3.1.3 requires php 7.2.* || 7.3.* -> your PHP version (7.4.6) does not satisfy that requirement.
    - Installation request for flobee/spss ^3.1 -> satisfiable by flobee/spss[3.1.3, 3.1.4].
```

**Comment by ripon1763** [comment]
Hello there,

I was trying to write a .sav file using the code below:

$writer = new \SPSS\Sav\Writer([
    'header' => [
            'prodName'     => '@(#) SPSS DATA FILE test',
            'layoutCode'   => 2,
            'compression'  => 1,
            'weightIndex'  => 0,
            'bias'         => 100,
            'creationDate' => '13 Feb 89',
            'creationTime' => '23:58:59',
    ],
    'variables' => [
        [
                'name'     => 'NAME',
                'width'    => 0,
                'decimals' => 0,
                'format'   => 5,
                'columns'  => 50,
                'align'    => 1,
                'measure'  => 1,
                'data'     => [
                    'Sagor','Kajol','Hasan'
                ]
        ]
    ]
]);

the error is below:
![isssue](https://user-images.githubusercontent.com/47550515/93857653-bea96a80-fcdc-11ea-8437-60e43a3fdff6.PNG)



I was inserting text as data here you see. Do I need to change the variables' values to process text data? What do the variables like 'decimals', 'format', 'columns', 'measure' mean specifically?

**Comment by flobee** [comment]
should be fixed already, insnt it?
