### ISSUE TITLE
How to set encoding?

### ISSUE THREAD

**Issue by semoriil** [flobee/spss#19]
I see Buffer class has such property, but I can't understand how to use it. It's unreachable from outside of Reader.

I have a lot of old *.sav files encoded in Windows-1251, but AFAIK it's marked as just "system" encoding, hence on different OS it's likely to be decoded in wrong way (like this lib on Linux). Also there may be some files in another old encoding.

So I need a way to force encoding to use.

**Comment by flobee** [comment]
sry for beeing late. I'm not in the topic at this time. no time.

Idea: convert old pspp/spss files in pspp/spss on a new OS with new versions of pspp/spss and save them new. !?
