### ISSUE TITLE
how to show .sav file in html table?

### ISSUE THREAD

**Issue by ahsannajam** [flobee/spss#2]
please guide me how to open .sav data in html table?

**Comment by flobee** [comment]
Implement a renderer which creates a html output.
OT (Off Topic): Please consult IBM/SPSS or PSPP Manufacturers or their Docs. 
There is no concrete answer to guide you. Use search engins to get into it. 
There are more easy ways to answer your question without using this program. sry. this program should not be used in web-server enviroment.
