### ISSUE TITLE
SPSS Variable length Issue

### ISSUE THREAD

**Issue by JobinReji** [flobee/spss#21]
Hi... I uploaded an SPSS file with the variable length of more than 8 characters. But it is taking the variable length of  first 8 characters. Is it possible to increase the variable length? If yes, let me know how to do the same.

Here I have provided the screenshots of the problem...

![Issue](https://github.com/flobee/spss/assets/64494857/463a78ec-0a8b-477d-9b89-8cfe9384e788)
![SPSS Original variable list](https://github.com/flobee/spss/assets/64494857/6e04b1bc-a732-45b7-959e-c882f5eb270e)

**Comment by manigandan-annadurai** [comment]
Have a same issue. Kindly check and let us know in a short time.

**Comment by mariankustusch** [comment]
For that you should use **LongVariableNames** class (src/Sav/Record/Info/LongVariableNames.php)

![image](https://github.com/flobee/spss/assets/30049465/56c1e420-8a96-4fd3-8776-b8229e3223d7)

**Comment by flobee** [comment]
pls check tiamo/spss. i'm not in the topic curently anymore...
