### ISSUE TITLE
variable values length issue

### ISSUE THREAD

**Issue by alcmoe** [flobee/spss#22]
![image](https://github.com/flobee/spss/assets/9844277/6c815ba5-e185-4d05-aed4-1ac41c140b77)
these variables' type is string, the second variable's length is 9(>8) ,so it goes,
![image](https://github.com/flobee/spss/assets/9844277/af1a9334-9c95-4eb5-ac3a-186a7a734881)
here, in $this->info[Record\Info\LongStringMissingValues::SUBTYPE].
them 
![image](https://github.com/flobee/spss/assets/9844277/4b9e2ba5-0d52-4ff5-9afe-44d2c5d10af4)
then write LongStringMissingValues buffer
![image](https://github.com/flobee/spss/assets/9844277/a5ef18c3-2118-4563-afee-39c3fbbd2f4f)
my language is Chinese，a Chinese character mb_strlen will return 1,but strlen will return 3, so mb_strlent('广州') will return 2。
so in my case, it should be  $localBuffer->writeString( $label, strlen( $label ) ); //('广州', 6);

**Comment by flobee** [comment]
sry. please check tiamo' releases: tiamo/spss. i can not support for the next time... or later
