### ISSUE TITLE
shows zero as missing data instead of 0

### ISSUE THREAD

**Issue by marco86to** [flobee/spss#4]
Hi, I am using the 2.0.1 version (as I have PHP7.0) to generate a .sav file. My problem is that I can't understand how to have all the zero. For example I have a column where I have sex: 0: f, 1:m as I will use a label to name them I have written 'format'   => Variable::FORMAT_TYPE_A, 'values' => [0 => 'Female', 1 => 'Male'],...
The problem is that all the 0 are as missing values! instead I would like to have the empty values only the real missing! any idea to fix this problem? 

Many thanks
Marco

**Comment by marco86to** [comment]
solution:
on Data.php line 274 I have edited the code as following:
`if ( (empty( $val )) and ($val !== "0") ) {`

hope that it would helpfull for someone else!

Marco

**Comment by flobee** [comment]
Right! in spss one should use values which are higher than zero because of those problems (or better to say: there where the data comes from eg. questback or other tools). in php its also a next special problem. use 1 for f and 2 for m. But thanks for the hint :)
