### ISSUE TITLE
Cannot open file in SPSS with 2 variables

### ISSUE THREAD

**Issue by pcholewa** [flobee/spss#5]
Hi!

When save file with below config, i cannot open saved file in SPSS - application hangs.

BUT, saved file opens success when:

-remove all variable 1 or 2
**OR**
-remove "width" from first variable
**OR**
-remove "values" from second variable

Anyone can help me? What i do wrong?

My code:
```
$writer = new \SPSS\Sav\Writer([
            'header' => [
                'prodName'     => '@(#) ' . $this->analysis->getName(),
                'layoutCode'   => 2,
                'compression'  => 1,
                'weightIndex'  => 0,
                'creationDate' => date('Y-m-d'),
                'creationTime' => date('H:i:s'),
            ],
            'variables' => [
                [
                    'name' => 'aaa',
                    'width' => 16,
                    'format' => 1,
                ],
                [
                    'name' => 'cc',
                    'format' => 5,
                    'values' => [
                        1 => 'Panel',
                    ]
                ],
            ]
        ]);
        $pathFile = 'spss.sav';
        $writer->save($pathFile);
```

**Comment by flobee** [comment]
Hi, create an spss like the same you want to create using this program and then compare with your setup.

**Comment by pcholewa** [comment]
Probably it's something wrong with writer. When i open saved (with writer) file, there are difference in array of variables - precisely in "print" and "write".
Additionally, when (in above code) i reverse order of variables it's open successfully in SPSS.

Can You check that? I would be very grateful :)
